env:
  global:
    - GCP_PROJECT_ID=exam-295817
    #Set which terraform version travis should install
    - tf_version=0.13.5
    #Disable google cloud sdk from asking prompts such as 'Are you sure...'
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
branches:
  only:
    #Only run travis on master branch
    - master

before_install:
  #Travis will decrypt our key file and use it
  - openssl aes-256-cbc -K $encrypted_61dc43fb09f9_key -iv $encrypted_61dc43fb09f9_iv -in terraform_keyfile.json.enc -out terraform_keyfile.json -d
  #Download google cloud sdk and install it
  - curl https://sdk.cloud.google.com | bash > /dev/null
  #Install google cloud
  - source "$HOME/google-cloud-sdk/path.bash.inc"
  #Authenticate in google cloud
  - gcloud auth activate-service-account --key-file=terraform_keyfile.json
  #Set active project
  - gcloud config set project "${GCP_PROJECT_ID}"
  #Set google_application_credentials to the decrypted file
  - export GOOGLE_APPLICATION_CREDENTIALS=./terraform_keyfile.json
  #Download terraform
  - wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
  #Unzip it
  - unzip terraform_"$tf_version"_linux_amd64.zip
  #Move the file
  - sudo mv terraform /usr/local/bin/
  #Remove the zip file for good-practise cleanup
  - rm terraform_"$tf_version"_linux_amd64.zip
install: true

script:
  - |-
    set -ex;
    terraform init
    terraform plan
    terraform apply --auto-approve
    terraform output